"""Language detection and workspace scaffolding for the Ollama Developer Assistant.

The Scaffolder agent runs before the Builder to create a clean, standard project
skeleton so the Builder always starts from a consistent, language-appropriate
layout rather than an empty directory.

Supported languages: python, node, rust, shell.
Unknown/undetected languages fall back to a generic skeleton.
"""

from __future__ import annotations

import re
from pathlib import Path

from .config import SETTINGS
from .workspace import resolve_safe_path


# ---------------------------------------------------------------------------
# Language detection
# ---------------------------------------------------------------------------

_LANG_PATTERNS: list[tuple[str, list[str]]] = [
    ("python", ["python", "py", "pip", "pyproject", "flask", "django", "fastapi", "pytest"]),
    ("node",   ["node", "javascript", "typescript", "npm", "yarn", "react", "express", "next"]),
    ("rust",   ["rust", "cargo", "crate", "tokio", "actix"]),
    ("shell",  ["bash", "shell", "sh script", "zsh", "posix"]),
]


def detect_language(text: str) -> str:
    """Return the best-matching language slug from architect/plan text, or 'generic'."""
    lower = text.lower()
    scores: dict[str, int] = {}
    for lang, keywords in _LANG_PATTERNS:
        scores[lang] = sum(1 for kw in keywords if kw in lower)
    best_lang, best_score = max(scores.items(), key=lambda kv: kv[1])
    return best_lang if best_score > 0 else "generic"


# ---------------------------------------------------------------------------
# Per-language skeleton factories
# ---------------------------------------------------------------------------

def _python_skeleton(root: Path, project_name: str) -> dict[str, str]:
    safe_name = re.sub(r"[^a-z0-9_]", "_", project_name.lower())
    return {
        "pyproject.toml": f"""\
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "{safe_name}"
version = "0.1.0"
description = "Generated by ollama-developer-assistant"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
{safe_name} = "{safe_name}.main:main"
""",
        f"src/{safe_name}/__init__.py": "",
        f"src/{safe_name}/main.py": f"""\
\"\"\"Entry point for {safe_name}.\"\"\"


def main() -> None:
    pass  # TODO: implement


if __name__ == "__main__":
    main()
""",
        "tests/__init__.py": "",
        "tests/test_main.py": f"""\
\"\"\"Scaffold placeholder tests — Test Engineer will fill these in.\"\"\"
from {safe_name}.main import main


def test_main_runs() -> None:
    main()  # should not raise
""",
        ".gitignore": "__pycache__/\n*.pyc\n*.egg-info/\ndist/\n.venv/\n",
        "README.md": f"# {project_name}\n\nGenerated by ollama-developer-assistant.\n",
    }


def _node_skeleton(root: Path, project_name: str) -> dict[str, str]:
    safe_name = re.sub(r"[^a-z0-9-]", "-", project_name.lower())
    return {
        "package.json": f"""\
{{
  "name": "{safe_name}",
  "version": "0.1.0",
  "description": "Generated by ollama-developer-assistant",
  "main": "src/index.js",
  "scripts": {{
    "start": "node src/index.js",
    "test": "node --test"
  }},
  "dependencies": {{}},
  "devDependencies": {{}}
}}
""",
        "src/index.js": "// Entry point\n\nmodule.exports = {};\n",
        "tests/index.test.js": "// Scaffold placeholder — Test Engineer will fill these in.\n",
        ".gitignore": "node_modules/\n*.log\n",
        "README.md": f"# {project_name}\n\nGenerated by ollama-developer-assistant.\n",
    }


def _rust_skeleton(root: Path, project_name: str) -> dict[str, str]:
    safe_name = re.sub(r"[^a-z0-9_]", "_", project_name.lower())
    return {
        "Cargo.toml": f"""\
[package]
name = "{safe_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
""",
        "src/main.rs": 'fn main() {\n    // TODO: implement\n}\n',
        "src/lib.rs": "// Library entry point\n",
        ".gitignore": "target/\n",
        "README.md": f"# {project_name}\n\nGenerated by ollama-developer-assistant.\n",
    }


def _shell_skeleton(root: Path, project_name: str) -> dict[str, str]:
    safe_name = re.sub(r"[^a-z0-9_-]", "_", project_name.lower())
    return {
        f"{safe_name}.sh": "#!/usr/bin/env bash\nset -euo pipefail\n\n# TODO: implement\n",
        "README.md": f"# {project_name}\n\nGenerated by ollama-developer-assistant.\n",
        ".gitignore": "*.log\n",
    }


def _generic_skeleton(root: Path, project_name: str) -> dict[str, str]:
    return {
        "README.md": f"# {project_name}\n\nGenerated by ollama-developer-assistant.\n",
        ".gitignore": "*.log\n",
        "main.txt": "# Project entry point placeholder\n",
    }


_FACTORIES = {
    "python": _python_skeleton,
    "node":   _node_skeleton,
    "rust":   _rust_skeleton,
    "shell":  _shell_skeleton,
    "generic": _generic_skeleton,
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def scaffold_project(architect_output: str, project_name: str = "my_project") -> dict[str, str]:
    """Detect language from *architect_output*, write skeleton files into the
    workspace root, and return a mapping of {relative_path: content} for all
    files that were written.

    Files that already exist are *not* overwritten — the Builder's earlier work
    is preserved.
    """
    root = Path(SETTINGS.workspace_root).resolve()
    lang = detect_language(architect_output)
    factory = _FACTORIES.get(lang, _generic_skeleton)
    files = factory(root, project_name)

    written: dict[str, str] = {}
    for rel_path, content in files.items():
        target = resolve_safe_path(str(root), rel_path)
        if not target.exists():
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            written[rel_path] = content

    return written
